### ISSUE TITLE
界面乱码

### ISSUE THREAD

**Issue by xp12047** [clearcdq/SpaceSniffer#1]
刚下载试了打开界面乱码。电脑系统刚升级的win 11 22h2

**Comment by clearcdq** [comment]
发个截图我看看



***@***.***
 
发件人： changcheng
发送时间： 2023-02-14 19:05
收件人： clearcdq/SpaceSniffer
抄送： Subscribed
主题： [clearcdq/SpaceSniffer] 界面乱码 (Issue #1)
刚下载试了打开界面乱码。电脑系统刚升级的win 11 22h2

**Comment by clearcdq** [comment]
你要去下载原件https://github.com/clearcdq/SpaceSniffer/blob/main/SpaceSniffer1.1.20%E6%B1%89%E5%8C%96%E7%89%88%20%20--%20%E7%A3%81%E7%9B%98%E6%96%87%E4%BB%B6%E5%88%86%E6%9E%90%E5%B7%A5%E5%85%B7.rar



***@***.***
 
发件人： changcheng
发送时间： 2023-02-14 19:05
收件人： clearcdq/SpaceSniffer
抄送： Subscribed
主题： [clearcdq/SpaceSniffer] 界面乱码 (Issue #1)
刚下载试了打开界面乱码。电脑系统刚升级的win 11 22h2

**Comment by xp12047** [comment]
> 

谢谢，当天就下载了原版。我想请教你个问题。怎么把我当前的系统做成iso镜像，方便在别的电脑上安装呢？
